### ISSUE TITLE
Need to document data- attributes

### ISSUE THREAD

**Issue by rouilj** [rameshvarun/blog-cells#11]
In looking at the demo page I see:
```
  data-autorun=true
  data-hidden=true
```
added to the script tag. Are there more?

**Comment by rameshvarun** [comment]
Those are the only ones supported currently.

Sorry for the sparse documentation. The project is definitely still evolving - be sure to pin a version when you import from a CDN.

**Comment by rameshvarun** [comment]
Added some more documentation to README.
