### ISSUE TITLE
Support Python

### ISSUE THREAD

**Issue by rameshvarun** [rameshvarun/blog-cells#8]
Already implemented here: https://blog.varunramesh.net/posts/simple-python-tips/

**Comment by theonewolf** [comment]
This is already complete?  Does it use Pyodide?

**Comment by rameshvarun** [comment]
I have my own fork of blog-cells using Pyodide. Before I merge it in, I want to set up a system where you can configure and select between multiple "kernels".

**Comment by rameshvarun** [comment]
Now available in v0.6.0
